/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 현재 런타임 상태 (GPU/메모리/모델 로드 여부).
         */
        get: operations["health_api_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect
         * @description 단일 이미지 감지 (동기).
         */
        post: operations["detect_api_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detect/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Batch
         * @description 배치 감지 (비동기 job).
         */
        post: operations["detect_batch_api_detect_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchJobResponse */
        BatchJobResponse: {
            /** Job Id */
            job_id: string;
        };
        /** Body_detect_api_detect_post */
        Body_detect_api_detect_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Use Sam
             * @default true
             */
            use_sam: boolean;
            /** Confidence */
            confidence?: number | null;
        };
        /** Body_detect_batch_api_detect_batch_post */
        Body_detect_batch_api_detect_batch_post: {
            /** Files */
            files: string[];
            /**
             * Use Sam
             * @default true
             */
            use_sam: boolean;
            /** Confidence */
            confidence?: number | null;
        };
        /** DetectMeta */
        DetectMeta: {
            /** Inference Ms */
            inference_ms: number;
            /** Num Detections */
            num_detections: number;
            /** Sam Used */
            sam_used: boolean;
            /** Yolo Model */
            yolo_model: string;
            /** Device */
            device?: string | null;
        };
        /** DetectResponse */
        DetectResponse: {
            /** Run Id */
            run_id: string;
            /** Detections */
            detections: components["schemas"]["DetectionItem"][];
            /** Annotated Image Url */
            annotated_image_url: string;
            meta: components["schemas"]["DetectMeta"];
        };
        /** DetectionItem */
        DetectionItem: {
            /**
             * Class
             * @description 영문 클래스명
             */
            class: string;
            /**
             * Class Kr
             * @description 한글 클래스명
             */
            class_kr: string;
            /** Score */
            score: number;
            /**
             * Bbox
             * @description [x1,y1,x2,y2]
             */
            bbox: number[];
            /**
             * Mask Url
             * @description SAM 마스크 PNG URL, 없으면 null
             */
            mask_url?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Gpu */
            gpu: {
                [key: string]: unknown;
            };
            /** Memory */
            memory: {
                [key: string]: unknown;
            };
            /** Models Loaded */
            models_loaded: {
                [key: string]: unknown;
            };
        };
        /** JobStatusResponse */
        JobStatusResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed";
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Done
             * @default 0
             */
            done: number;
            /** Results */
            results?: components["schemas"]["DetectResponse"][] | null;
            /** Error */
            error?: string | null;
        };
        /** ModelsResponse */
        ModelsResponse: {
            /** Yolo */
            yolo: {
                [key: string]: string;
            };
            /** Sam */
            sam: {
                [key: string]: string;
            };
            /** Default Yolo */
            default_yolo: string;
            /** Default Sam */
            default_sam: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    detect_api_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_detect_api_detect_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detect_batch_api_detect_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_detect_batch_api_detect_batch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchJobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
